# Generated by Django 4.2.7 on 2023-11-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='chi.jpg', upload_to='profile_pics'),
        ),
    ]
